name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Make
        run: choco install make

      - name: Install GCC
        run: choco install mingw

      - name: Run build script
        run: .\build.bat

      - name: Archive bounceyerror.exe
        run: |
          cd output
          Compress-Archive -Path bouncyerror.exe -DestinationPath "BouncyError.zip"

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: BouncyError
          path: output/BouncyError.zip
